#!/bin/bash

# Mission: Combine what you've learned! Write a script that:
# 1. Creates a directory names 'Battlefield'
# 2. Inside Battlefield, create files named knight.txt, sorcerer.txt, and rogue.txt
# 3. Check if knight.txt exists; if it does, move it to a new directory called Archive
# 4. List the contents of both Battlefield and Archive

mkdir -p Battlefield
touch Battlefield/{knight,sorcerer,rogue}.txt

if [ -f knight.txt ];then
    cd ..
    mkdir Archive
    cp -r Battlefield/knight.txt Archive
    ls Battlefield Archive
fi
